### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "kobil@kippa.africa",
    "username": "Salim Kobi",
    "password": "kobi"
}

### Signin an existing user

POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "kobil@kippa.africa",
    "password": "kobi"
}

### Signout the currently signed in user
POST http://localhost:3000/auth/signout

### Find a particular user with ID
   
GET http://localhost:3000/auth/2

### Find all users registered with a given email

GET http://localhost:3000/auth?email=asdf@asdf.com


### Delete a user with a given ID
DELETE http://localhost:3000/auth/15


### Update a user with a given ID
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "victor@kippa.africa"
}

### Get the currently signed in user

GET http://localhost:3000/auth/whoami